network:
	ethernets:
		ens34:
			dhcp4: false
			addresses:
			- 192.168.100.248/24			# we must add /24 subnet, which is a subnet mask of 255.255.255.0
			routes:
			- to: default
			  via: 192.168.100.1			# we have to add gateway ip address
			nameservers:
			  addresses: [8.8.8.8]
	version: 2
